substitutions:
  name: "aquaha"
  friendly_name: "AquaHA"
  app_version: "1.0.2"

packages:
  core: !include aquaha_files/core.yaml
  alarms: !include aquaha_files/alarms.yaml
  ds18b20: !include aquaha_files/ds18b20.yaml
  ezo_ph: !include aquaha_files/ezo_ph.yaml
  #ezo_ec: !include aquaha_files/ezo_ec.yaml
  ezo_do: !include aquaha_files/ezo_do.yaml
  heating: !include aquaha_files/heating.yaml
  lights: !include aquaha_files/lights.yaml
  time_scheduler: !include aquaha_files/time_scheduler.yaml
  ultrasonic_distance: !include aquaha_files/ultrasonic_distance.yaml

esphome:
  min_version: 2024.6.0
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  comment: "AquaHA - Aquarium Controller for Home Assistant"
  project:
    name: "sebsz.aquaha"
    version: "${app_version}"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

api:

ota:
  platform: esphome

logger:
  level: "DEBUG"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://SeBsZ/AquaHA/aquaha_config_ph_do.yaml@main
  import_full_config: false # or true

wifi:
  ap:
    password: "aquaHAaquaHA"

captive_portal: