one_wire:
  - platform: gpio
    pin: GPIO23
    id: one_wire_1
  - platform: gpio
    pin: GPIO5
    id: one_wire_2

sensor:
  - platform: dallas_temp
    name: temp1
    id: temp1
    update_interval: "60s"
    one_wire_id: one_wire_1
    on_value:
      then:
      - if:
          condition: 
            - sensor.in_range:
                id: temp1
                above: 0.5
            - switch.is_on: enable_temperature_compensation
          then:
            - button.press: write_temp_comp
  - platform: dallas_temp
    name: temp2
    id: temp2
    update_interval: "60s"
    one_wire_id: one_wire_2

button:
  - platform: template
    id: write_temp_comp
    internal: true
    on_press:
      then:
        - if:
            condition: 
              - sensor.in_range:
                  id: temp1
                  above: 0.5
              - switch.is_on: enable_temperature_compensation
            then:
              - lambda: |-
                  if (id(ph_module).state == 'true') {
                    id(write_temp_comp_ph).press();
                  }
                  if (id(ec_module).state == 'true') {
                    id(write_temp_comp_ec).press();
                  }
                  if (id(do_module).state == 'true') {
                    id(write_temp_comp_do).press();
                  }
        
  - platform: template
    id: reset_temp_comp
    internal: true
    on_press:
      - lambda: |-
          if (id(ph_module).state == 'true') {
            id(reset_temp_comp_ph).press();
          }
          if (id(ec_module).state == 'true') {
            id(reset_temp_comp_ec).press();
          }
          if (id(do_module).state == 'true') {
            id(reset_temp_comp_do).press();
          }
