sensor:
  - platform: ezo
    icon: mdi:ph
    name: "pH"
    id: ph_ezo
    address: ${ph_address}
    unit_of_measurement: ""
    accuracy_decimals: 2
    update_interval: 1s
    state_class: "measurement"
    device_class: PH
    on_custom: 
      then:
        - lambda: 
            id(ph_result).publish_state(x);
    on_calibration: 
      then:
        - lambda: 
            id(ph_result).publish_state(x);
    on_device_information: 
      then:
        - lambda: 
            id(ph_result).publish_state(x);
    on_slope: 
      then:
        - lambda: 
            id(ph_result).publish_state(x);
    on_t: 
      then:
        - lambda: 
            id(ph_result).publish_state(x); 
  - platform: copy
    source_id: ph_ezo
    id: ph_avg
    icon: mdi:ph
    name: "pH avg"
    state_class: "measurement"
    device_class: PH
    accuracy_decimals: 2
    filters:
      - sliding_window_moving_average: 
          window_size: 60
          send_every: 60
          send_first_at: 30

text_sensor:
  - platform: template
    name: pH - Result
    id: ph_result
    # disabled_by_default: true

button:
  - platform: template
    name: pH - Take reading
    id: ph_read
    icon: mdi:read
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            id(ph_ezo).send_custom("R");
  - platform: template
    name: pH - Send command
    id: ph_send_command
    entity_category: "Config"
    on_press:
      then:
        - lambda: |-
            if (id(ph_select_command).state == "Read") {
              id(ph_ezo).send_custom("R");
            }
            if (id(ph_select_command).state == "Information") {
              id(ph_ezo).get_device_information();
            }
            if (id(ph_select_command).state == "Status") {
              id(ph_ezo).send_custom("Status");
            }
            if (id(ph_select_command).state == "Get Slope") {
              id(ph_ezo).get_slope();
            }
            if (id(ph_select_command).state == "Check Calibration") {
              id(ph_ezo).get_calibration();
            }  
            if (id(ph_select_command).state == "CLEAR Calibration") {
              id(ph_ezo).clear_calibration();
            }
            if (id(ph_select_command).state == "Calibrate pH 4") {
              id(ph_ezo).set_calibration_point_low(4.00);
            }
            if (id(ph_select_command).state == "Calibrate pH 7") {
              id(ph_ezo).set_calibration_point_mid(7.00);
            }
            if (id(ph_select_command).state == "Calibrate pH 9") {
              id(ph_ezo).set_calibration_point_high(9.00);
            }
            if (id(ph_select_command).state == "Calibrate pH 10") {
              id(ph_ezo).set_calibration_point_high(10.00);
            }

select:
  - platform: template
    name: pH Select Command
    id: ph_select_command
    optimistic: true
    # disabled_by_default: true
    entity_category: "Config"
    options:
      - "Read"
      - "Information"
      - "Status"
      - "Get Slope"
      - "Check Calibration"
      - "Calibrate pH 4"
      - "Calibrate pH 7"
      - "Calibrate pH 9"
      - "Calibrate pH 10"
      - "CLEAR Calibration"
    initial_option: "Check Calibration"
    set_action:
      - logger.log:
          format: "Chosen option: %s"
          args: ["x.c_str()"]
