time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Brussels
    servers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org

switch:
  - platform: template
    name: "Enable Light 1 Schedule"
    id: enable_light1_schedule
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: "Enable Light 2 Schedule"
    id: enable_light2_schedule
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: "Enable Light 3 Schedule"
    id: enable_light3_schedule
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: template
    name: "Enable Light 4 Schedule"
    id: enable_light4_schedule
    optimistic: True
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: template
    id: light1_brightness
    icon: mdi:target-variant
    name: "Light 1 Brightness"
    update_interval: never
    unit_of_measurement: "%"
    device_class: "illuminance"
    state_class: "measurement"
    accuracy_decimals: 1
  - platform: template
    id: light2_brightness
    icon: mdi:target-variant
    name: "Light 2 Brightness"
    update_interval: never
    unit_of_measurement: "%"
    device_class: "illuminance"
    state_class: "measurement"
  - platform: template
    id: light3_brightness
    icon: mdi:target-variant
    name: "Light 3 Brightness"
    update_interval: never
    unit_of_measurement: "%"
    device_class: "illuminance"
    state_class: "measurement"
  - platform: template
    id: light4_brightness
    icon: mdi:target-variant
    name: "Light 4 Brightness"
    unit_of_measurement: "%"
    update_interval: never
    device_class: "illuminance"
    state_class: "measurement"

select:
  # Setpoint 1 hour
  - platform: template
    name: "Lights setpoint 1 hour"
    id: setpoint1_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 1 minute
  - platform: template
    name: "Lights setpoint 1 minute"
    id: setpoint1_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 2 hour
  - platform: template
    name: "Lights setpoint 2 hour"
    id: setpoint2_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 2 minute
  - platform: template
    name: "Lights setpoint 2 minute"
    id: setpoint2_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 3 hour
  - platform: template
    name: "Lights setpoint 3 hour"
    id: setpoint3_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 3 minute
  - platform: template
    name: "Lights setpoint 3 minute"
    id: setpoint3_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 4 hour
  - platform: template
    name: "Lights setpoint 4 hour"
    id: setpoint4_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 4 minute
  - platform: template
    name: "Lights setpoint 4 minute"
    id: setpoint4_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 5 hour
  - platform: template
    name: "Lights setpoint 5 hour"
    id: setpoint5_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 5 minute
  - platform: template
    name: "Lights setpoint 5 minute"
    id: setpoint5_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 6 hour
  - platform: template
    name: "Lights setpoint 6 hour"
    id: setpoint6_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 6 minute
  - platform: template
    name: "Lights setpoint 6 minute"
    id: setpoint6_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 7 hour
  - platform: template
    name: "Lights setpoint 7 hour"
    id: setpoint7_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 7 minute
  - platform: template
    name: "Lights setpoint 7 minute"
    id: setpoint7_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Setpoint 8 hour
  - platform: template
    name: "Lights setpoint 8 hour"
    id: setpoint8_hour
    options: ["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"]
    restore_value: True
    optimistic: True

  # Setpoint 8 minute
  - platform: template
    name: "Lights setpoint 8 minute"
    id: setpoint8_minute
    options: ["0","15","30","45"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 1 (brightness)
  - platform: template
    name: "Light 1 setpoint 1"
    id: setpoint1_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 2 (brightness)
  - platform: template
    name: "Light 1 setpoint 2"
    id: setpoint2_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 3 (brightness)
  - platform: template
    name: "Light 1 setpoint 3"
    id: setpoint3_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 4 (brightness)
  - platform: template
    name: "Light 1 setpoint 4"
    id: setpoint4_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 5 (brightness)
  - platform: template
    name: "Light 1 setpoint 5"
    id: setpoint5_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 6 (brightness)
  - platform: template
    name: "Light 1 setpoint 6"
    id: setpoint6_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 7 (brightness)
  - platform: template
    name: "Light 1 setpoint 7"
    id: setpoint7_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 1 setpoint 8 (brightness)
  - platform: template
    name: "Light 1 setpoint 8"
    id: setpoint8_brightness1
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 1 (brightness)
  - platform: template
    name: "Light 2 setpoint 1"
    id: setpoint1_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 2 (brightness)
  - platform: template
    name: "Light 2 setpoint 2"
    id: setpoint2_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 3 (brightness)
  - platform: template
    name: "Light 2 setpoint 3"
    id: setpoint3_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 4 (brightness)
  - platform: template
    name: "Light 2 setpoint 4"
    id: setpoint4_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 5 (brightness)
  - platform: template
    name: "Light 2 setpoint 5"
    id: setpoint5_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 6 (brightness)
  - platform: template
    name: "Light 2 setpoint 6"
    id: setpoint6_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 7 (brightness)
  - platform: template
    name: "Light 2 setpoint 7"
    id: setpoint7_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 2 setpoint 8 (brightness)
  - platform: template
    name: "Light 2 setpoint 8"
    id: setpoint8_brightness2
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 1 (brightness)
  - platform: template
    name: "Light 3 setpoint 1"
    id: setpoint1_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 2 (brightness)
  - platform: template
    name: "Light 3 setpoint 2"
    id: setpoint2_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 3 (brightness)
  - platform: template
    name: "Light 3 setpoint 3"
    id: setpoint3_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 4 (brightness)
  - platform: template
    name: "Light 3 setpoint 4"
    id: setpoint4_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 5 (brightness)
  - platform: template
    name: "Light 3 setpoint 5"
    id: setpoint5_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 6 (brightness)
  - platform: template
    name: "Light 3 setpoint 6"
    id: setpoint6_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 7 (brightness)
  - platform: template
    name: "Light 3 setpoint 7"
    id: setpoint7_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 3 setpoint 8 (brightness)
  - platform: template
    name: "Light 3 setpoint 8"
    id: setpoint8_brightness3
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 1 (brightness)
  - platform: template
    name: "Light 4 setpoint 1"
    id: setpoint1_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 2 (brightness)
  - platform: template
    name: "Light 4 setpoint 2"
    id: setpoint2_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 3 (brightness)
  - platform: template
    name: "Light 4 setpoint 3"
    id: setpoint3_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 4 (brightness)
  - platform: template
    name: "Light 4 setpoint 4"
    id: setpoint4_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 5 (brightness)
  - platform: template
    name: "Light 4 setpoint 5"
    id: setpoint5_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 6 (brightness)
  - platform: template
    name: "Light 4 setpoint 6"
    id: setpoint6_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 7 (brightness)
  - platform: template
    name: "Light 4 setpoint 7"
    id: setpoint7_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

  # Light 4 setpoint 8 (brightness)
  - platform: template
    name: "Light 4 setpoint 8"
    id: setpoint8_brightness4
    options: ["0","5","7","10","20","30","40","50","60","70","80","90","100"]
    restore_value: True
    optimistic: True

text_sensor:
  - platform: template
    name: "Current Time"
    id: current_time
    update_interval: 60s
    lambda: return  id(sntp_time).now().strftime("%H:%M:%S");

interval:
- interval: 60s
  then:
    - lambda: |-
        auto time_now = id(sntp_time).now();
        int total_minutes = time_now.hour * 60 + time_now.minute;

        // Define the 8 setpoints and their corresponding brightness levels
        const int time_setpoints[8] = {
            atoi(id(setpoint1_hour).state.c_str()) * 60 + atoi(id(setpoint1_minute).state.c_str()),
            atoi(id(setpoint2_hour).state.c_str()) * 60 + atoi(id(setpoint2_minute).state.c_str()),
            atoi(id(setpoint3_hour).state.c_str()) * 60 + atoi(id(setpoint3_minute).state.c_str()),
            atoi(id(setpoint4_hour).state.c_str()) * 60 + atoi(id(setpoint4_minute).state.c_str()),
            atoi(id(setpoint5_hour).state.c_str()) * 60 + atoi(id(setpoint5_minute).state.c_str()),
            atoi(id(setpoint6_hour).state.c_str()) * 60 + atoi(id(setpoint6_minute).state.c_str()),
            atoi(id(setpoint7_hour).state.c_str()) * 60 + atoi(id(setpoint7_minute).state.c_str()),
            atoi(id(setpoint8_hour).state.c_str()) * 60 + atoi(id(setpoint8_minute).state.c_str())
        };

        const float brightness_levels1[8] = {
            static_cast<float>(atof(id(setpoint1_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint2_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint3_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint4_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint5_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint6_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint7_brightness1).state.c_str())),
            static_cast<float>(atof(id(setpoint8_brightness1).state.c_str()))
        };

        const float brightness_levels2[8] = {
            static_cast<float>(atof(id(setpoint1_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint2_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint3_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint4_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint5_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint6_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint7_brightness2).state.c_str())),
            static_cast<float>(atof(id(setpoint8_brightness2).state.c_str()))
        };

        const float brightness_levels3[8] = {
            static_cast<float>(atof(id(setpoint1_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint2_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint3_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint4_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint5_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint6_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint7_brightness3).state.c_str())),
            static_cast<float>(atof(id(setpoint8_brightness3).state.c_str()))
        };

        const float brightness_levels4[8] = {
            static_cast<float>(atof(id(setpoint1_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint2_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint3_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint4_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint5_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint6_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint7_brightness4).state.c_str())),
            static_cast<float>(atof(id(setpoint8_brightness4).state.c_str()))
        };

        // Default brightness (fallback)
        float brightness1 = brightness_levels1[0];
        float brightness2 = brightness_levels2[0];
        float brightness3 = brightness_levels3[0];
        float brightness4 = brightness_levels4[0];

        // Find the correct segment for interpolation
        for (int i = 0; i < 8; i++) {
          int t1 = time_setpoints[i];
          int t2 = time_setpoints[(i + 1) % 8]; // Wrap around to the first setpoint
          float b1_1 = brightness_levels1[i];
          float b2_1 = brightness_levels1[(i + 1) % 8];

          float b1_2 = brightness_levels2[i];
          float b2_2 = brightness_levels2[(i + 1) % 8];

          float b1_3 = brightness_levels3[i];
          float b2_3 = brightness_levels3[(i + 1) % 8];

          float b1_4 = brightness_levels4[i];
          float b2_4 = brightness_levels4[(i + 1) % 8];

          if (t1 <= total_minutes && total_minutes < t2) {
            // Calculate progress and interpolate brightness for each light
            float progress = float(total_minutes - t1) / (t2 - t1);
            brightness1 = b1_1 + progress * (b2_1 - b1_1);
            brightness2 = b1_2 + progress * (b2_2 - b1_2);
            brightness3 = b1_3 + progress * (b2_3 - b1_3);
            brightness4 = b1_4 + progress * (b2_4 - b1_4);
            break;
          }
        }

        // Set the actual light's brightnesses
        if (id(enable_light1_schedule).state) {
          id(led_output_1).turn_on().set_brightness(brightness1 / 100.0).perform();
        }
        id(light1_brightness).publish_state(brightness1);
        
        if (id(enable_light2_schedule).state) {
          id(led_output_2).turn_on().set_brightness(brightness2 / 100.0).perform();
        }
        id(light2_brightness).publish_state(brightness2);
        
        if (id(enable_light3_schedule).state) {
          id(led_output_3).turn_on().set_brightness(brightness3 / 100.0).perform();
        }
        id(light3_brightness).publish_state(brightness3);
        
        if (id(enable_light4_schedule).state) {
          id(led_output_4).turn_on().set_brightness(brightness4 / 100.0).perform();
        }
        id(light4_brightness).publish_state(brightness4);